################################################
################################################
################################################
#########*******###*******####**********########
########**#####**#**#####**###**######**########
########**#####**#**#####**###**######**########
########**#####**#**#####**###**********########
########**#####**#**#####**###**################
########**#####**#**#####**###**################
########**######***######**###**################
########**###############**###**################
########**###############**###**################
################################################
########Copyright © Maresal Programming#########
################################################

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 751)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.MenuFrame = QtWidgets.QFrame(self.centralwidget)
        self.MenuFrame.setMinimumSize(QtCore.QSize(150, 0))
        self.MenuFrame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.MenuFrame.setStyleSheet("")
        self.MenuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MenuFrame.setObjectName("MenuFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.MenuFrame)
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.homeBtn = QtWidgets.QPushButton(self.MenuFrame)
        self.homeBtn.setMinimumSize(QtCore.QSize(150, 50))
        self.homeBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout.addWidget(self.homeBtn)
        self.filmsBtn = QtWidgets.QPushButton(self.MenuFrame)
        self.filmsBtn.setMinimumSize(QtCore.QSize(150, 50))
        self.filmsBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.filmsBtn.setObjectName("filmsBtn")
        self.verticalLayout.addWidget(self.filmsBtn)
        self.filmAddBtn = QtWidgets.QPushButton(self.MenuFrame)
        self.filmAddBtn.setMinimumSize(QtCore.QSize(150, 50))
        self.filmAddBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.filmAddBtn.setObjectName("filmAddBtn")
        self.verticalLayout.addWidget(self.filmAddBtn)
        spacerItem = QtWidgets.QSpacerItem(45, 257, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.registerHomeBtn = QtWidgets.QPushButton(self.MenuFrame)
        self.registerHomeBtn.setMinimumSize(QtCore.QSize(150, 50))
        self.registerHomeBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.registerHomeBtn.setObjectName("registerHomeBtn")
        self.verticalLayout.addWidget(self.registerHomeBtn)
        self.LoginBtn = QtWidgets.QPushButton(self.MenuFrame)
        self.LoginBtn.setMinimumSize(QtCore.QSize(150, 50))
        self.LoginBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.LoginBtn.setObjectName("LoginBtn")
        self.verticalLayout.addWidget(self.LoginBtn)
        self.LogoutBtn = QtWidgets.QPushButton(self.MenuFrame)
        self.LogoutBtn.setMinimumSize(QtCore.QSize(150, 50))
        self.LogoutBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.LogoutBtn.setObjectName("LogoutBtn")
        self.verticalLayout.addWidget(self.LogoutBtn)
        self.settingBtn = QtWidgets.QPushButton(self.MenuFrame)
        self.settingBtn.setMinimumSize(QtCore.QSize(150, 50))
        self.settingBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.settingBtn.setObjectName("settingBtn")
        self.verticalLayout.addWidget(self.settingBtn)
        self.gridLayout.addWidget(self.MenuFrame, 1, 0, 1, 1)
        self.PageFrame = QtWidgets.QFrame(self.centralwidget)
        self.PageFrame.setStyleSheet("")
        self.PageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PageFrame.setObjectName("PageFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.PageFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.PageFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.HomePage = QtWidgets.QWidget()
        self.HomePage.setObjectName("HomePage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.HomePage)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.HomePage)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.HomePage)
        self.FilmsPage = QtWidgets.QWidget()
        self.FilmsPage.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.FilmsPage.setStyleSheet("#FilmsPage{background-color: rgb(54, 54, 54);}")
        self.FilmsPage.setObjectName("FilmsPage")
        self.FilmPageGridLayout = QtWidgets.QGridLayout(self.FilmsPage)
        self.FilmPageGridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.FilmPageGridLayout.setObjectName("FilmPageGridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.FilmsPage)
        self.scrollArea.setStyleSheet("#FilmsPage{background-color: rgb(54, 54, 54);}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 908, 642))
        self.scrollAreaWidgetContents.setStyleSheet("#scrollAreaWidgetContents{background-color: rgb(54, 54, 54);}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.FilmPageGridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.FilmPageGridLayout_2.setObjectName("FilmPageGridLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.FilmPageGridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.FilmsPage)
        self.FilmPage = QtWidgets.QWidget()
        self.FilmPage.setStyleSheet("")
        self.FilmPage.setObjectName("FilmPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.FilmPage)
        self.gridLayout_4.setContentsMargins(-1, -1, 5, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalSlider = QtWidgets.QSlider(self.FilmPage)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_4.addWidget(self.horizontalSlider, 5, 1, 1, 1)
        self.vizyonThLbl = QtWidgets.QLabel(self.FilmPage)
        self.vizyonThLbl.setMinimumSize(QtCore.QSize(250, 15))
        self.vizyonThLbl.setObjectName("vizyonThLbl")
        self.gridLayout_4.addWidget(self.vizyonThLbl, 1, 3, 1, 1)
        self.VideoWidget = QVideoWidget(self.FilmPage)
        self.VideoWidget.setMinimumSize(QtCore.QSize(640, 360))
        self.VideoWidget.setStyleSheet("#VideoWidget{\n"
"background-color:white;\n"
"}")
        self.VideoWidget.setObjectName("VideoWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.VideoWidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4.addWidget(self.VideoWidget, 0, 0, 5, 2)
        self.OzetLbl = QtWidgets.QLabel(self.FilmPage)
        self.OzetLbl.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.OzetLbl.setFont(font)
        self.OzetLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.OzetLbl.setObjectName("OzetLbl")
        self.gridLayout_4.addWidget(self.OzetLbl, 6, 0, 1, 2)
        self.originalNameLbl = QtWidgets.QLabel(self.FilmPage)
        self.originalNameLbl.setMinimumSize(QtCore.QSize(250, 15))
        self.originalNameLbl.setObjectName("originalNameLbl")
        self.gridLayout_4.addWidget(self.originalNameLbl, 4, 3, 1, 1)
        self.filmNameLbl = QtWidgets.QLabel(self.FilmPage)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.filmNameLbl.setFont(font)
        self.filmNameLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.filmNameLbl.setObjectName("filmNameLbl")
        self.gridLayout_4.addWidget(self.filmNameLbl, 0, 3, 1, 1)
        self.videoBtn = QtWidgets.QPushButton(self.FilmPage)
        self.videoBtn.setText("")
        self.videoBtn.setObjectName("videoBtn")
        self.gridLayout_4.addWidget(self.videoBtn, 5, 0, 1, 1)
        self.categoryFilmLbl = QtWidgets.QLabel(self.FilmPage)
        self.categoryFilmLbl.setMinimumSize(QtCore.QSize(250, 15))
        self.categoryFilmLbl.setObjectName("categoryFilmLbl")
        self.gridLayout_4.addWidget(self.categoryFilmLbl, 3, 3, 1, 1)
        self.ozetTxtedt = QtWidgets.QTextEdit(self.FilmPage)
        self.ozetTxtedt.setObjectName("ozetTxtedt")
        self.gridLayout_4.addWidget(self.ozetTxtedt, 7, 0, 1, 2)
        self.directorNameLbl = QtWidgets.QLabel(self.FilmPage)
        self.directorNameLbl.setMinimumSize(QtCore.QSize(250, 15))
        self.directorNameLbl.setObjectName("directorNameLbl")
        self.gridLayout_4.addWidget(self.directorNameLbl, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(15, 25, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 2, 2, 1, 1)
        self.stackedWidget.addWidget(self.FilmPage)
        self.FilmAddPage = QtWidgets.QWidget()
        self.FilmAddPage.setObjectName("FilmAddPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.FilmAddPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.filmFrgVideoTbx = QtWidgets.QLineEdit(self.FilmAddPage)
        self.filmFrgVideoTbx.setMinimumSize(QtCore.QSize(0, 30))
        self.filmFrgVideoTbx.setObjectName("filmFrgVideoTbx")
        self.gridLayout_2.addWidget(self.filmFrgVideoTbx, 10, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.FilmAddPage)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.FilmAddPage)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 1)
        self.vizyonTrhTbx = QtWidgets.QLineEdit(self.FilmAddPage)
        self.vizyonTrhTbx.setMinimumSize(QtCore.QSize(0, 30))
        self.vizyonTrhTbx.setObjectName("vizyonTrhTbx")
        self.gridLayout_2.addWidget(self.vizyonTrhTbx, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.FilmAddPage)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.filmImgTbx = QtWidgets.QLineEdit(self.FilmAddPage)
        self.filmImgTbx.setMinimumSize(QtCore.QSize(0, 30))
        self.filmImgTbx.setObjectName("filmImgTbx")
        self.gridLayout_2.addWidget(self.filmImgTbx, 7, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.FilmAddPage)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.FilmAddPage)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.FilmAddPage)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 11, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 2)
        self.filmKayitLbl = QtWidgets.QLabel(self.FilmAddPage)
        self.filmKayitLbl.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.filmKayitLbl.setFont(font)
        self.filmKayitLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.filmKayitLbl.setObjectName("filmKayitLbl")
        self.gridLayout_2.addWidget(self.filmKayitLbl, 0, 0, 1, 2)
        self.filmCategoryTbx = QtWidgets.QLineEdit(self.FilmAddPage)
        self.filmCategoryTbx.setMinimumSize(QtCore.QSize(0, 30))
        self.filmCategoryTbx.setObjectName("filmCategoryTbx")
        self.gridLayout_2.addWidget(self.filmCategoryTbx, 5, 0, 1, 1)
        self.clearBtn = QtWidgets.QPushButton(self.FilmAddPage)
        self.clearBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.clearBtn.setObjectName("clearBtn")
        self.gridLayout_2.addWidget(self.clearBtn, 14, 1, 1, 1)
        self.filmNameTbx = QtWidgets.QLineEdit(self.FilmAddPage)
        self.filmNameTbx.setMinimumSize(QtCore.QSize(0, 30))
        self.filmNameTbx.setObjectName("filmNameTbx")
        self.gridLayout_2.addWidget(self.filmNameTbx, 3, 0, 1, 1)
        self.ozetTbx = QtWidgets.QTextEdit(self.FilmAddPage)
        self.ozetTbx.setObjectName("ozetTbx")
        self.gridLayout_2.addWidget(self.ozetTbx, 13, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.FilmAddPage)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 9, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.FilmAddPage)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 1, 1, 1)
        self.saveFilmBtn = QtWidgets.QPushButton(self.FilmAddPage)
        self.saveFilmBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.saveFilmBtn.setObjectName("saveFilmBtn")
        self.gridLayout_2.addWidget(self.saveFilmBtn, 14, 0, 1, 1)
        self.directorNameTbx = QtWidgets.QLineEdit(self.FilmAddPage)
        self.directorNameTbx.setMinimumSize(QtCore.QSize(0, 30))
        self.directorNameTbx.setObjectName("directorNameTbx")
        self.gridLayout_2.addWidget(self.directorNameTbx, 3, 1, 1, 1)
        self.filmOriginalNameTbx = QtWidgets.QLineEdit(self.FilmAddPage)
        self.filmOriginalNameTbx.setMinimumSize(QtCore.QSize(0, 30))
        self.filmOriginalNameTbx.setObjectName("filmOriginalNameTbx")
        self.gridLayout_2.addWidget(self.filmOriginalNameTbx, 5, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.FilmAddPage)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 15, 0, 1, 2)
        self.stackedWidget.addWidget(self.FilmAddPage)
        self.Register_LoginPage = QtWidgets.QWidget()
        self.Register_LoginPage.setObjectName("Register_LoginPage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Register_LoginPage)
        self.gridLayout_3.setVerticalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.securityQLbl = QtWidgets.QLabel(self.Register_LoginPage)
        self.securityQLbl.setMinimumSize(QtCore.QSize(250, 15))
        self.securityQLbl.setMaximumSize(QtCore.QSize(250, 15))
        self.securityQLbl.setObjectName("securityQLbl")
        self.gridLayout_3.addWidget(self.securityQLbl, 11, 1, 1, 1)
        self.usernameLbl = QtWidgets.QLabel(self.Register_LoginPage)
        self.usernameLbl.setMinimumSize(QtCore.QSize(250, 15))
        self.usernameLbl.setMaximumSize(QtCore.QSize(250, 15))
        self.usernameLbl.setObjectName("usernameLbl")
        self.gridLayout_3.addWidget(self.usernameLbl, 1, 1, 1, 1)
        self.LoginLogoLbl = QtWidgets.QLabel(self.Register_LoginPage)
        self.LoginLogoLbl.setMaximumSize(QtCore.QSize(250, 250))
        self.LoginLogoLbl.setText("")
        self.LoginLogoLbl.setObjectName("LoginLogoLbl")
        self.gridLayout_3.addWidget(self.LoginLogoLbl, 0, 1, 1, 1)
        self.emailLbl = QtWidgets.QLabel(self.Register_LoginPage)
        self.emailLbl.setMinimumSize(QtCore.QSize(250, 15))
        self.emailLbl.setMaximumSize(QtCore.QSize(250, 15))
        self.emailLbl.setObjectName("emailLbl")
        self.gridLayout_3.addWidget(self.emailLbl, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(320, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 2, 1, 1)
        self.securityQuestionTbx = QtWidgets.QLineEdit(self.Register_LoginPage)
        self.securityQuestionTbx.setMinimumSize(QtCore.QSize(250, 30))
        self.securityQuestionTbx.setMaximumSize(QtCore.QSize(250, 30))
        self.securityQuestionTbx.setObjectName("securityQuestionTbx")
        self.gridLayout_3.addWidget(self.securityQuestionTbx, 12, 1, 1, 1)
        self.pwTbx_2 = QtWidgets.QLineEdit(self.Register_LoginPage)
        self.pwTbx_2.setMinimumSize(QtCore.QSize(250, 30))
        self.pwTbx_2.setMaximumSize(QtCore.QSize(250, 30))
        self.pwTbx_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwTbx_2.setObjectName("pwTbx_2")
        self.gridLayout_3.addWidget(self.pwTbx_2, 6, 1, 1, 1)
        self.loginBtn = QtWidgets.QPushButton(self.Register_LoginPage)
        self.loginBtn.setMinimumSize(QtCore.QSize(250, 30))
        self.loginBtn.setObjectName("loginBtn")
        self.gridLayout_3.addWidget(self.loginBtn, 13, 1, 1, 1)
        self.pwLbl2 = QtWidgets.QLabel(self.Register_LoginPage)
        self.pwLbl2.setMinimumSize(QtCore.QSize(250, 15))
        self.pwLbl2.setMaximumSize(QtCore.QSize(250, 15))
        self.pwLbl2.setObjectName("pwLbl2")
        self.gridLayout_3.addWidget(self.pwLbl2, 7, 1, 1, 1)
        self.e_mailTbx = QtWidgets.QLineEdit(self.Register_LoginPage)
        self.e_mailTbx.setMinimumSize(QtCore.QSize(250, 30))
        self.e_mailTbx.setMaximumSize(QtCore.QSize(250, 30))
        self.e_mailTbx.setObjectName("e_mailTbx")
        self.gridLayout_3.addWidget(self.e_mailTbx, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(320, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 0, 1, 1)
        self.registerBtn = QtWidgets.QPushButton(self.Register_LoginPage)
        self.registerBtn.setMinimumSize(QtCore.QSize(250, 30))
        self.registerBtn.setObjectName("registerBtn")
        self.gridLayout_3.addWidget(self.registerBtn, 14, 1, 1, 1)
        self.usernameTbx = QtWidgets.QLineEdit(self.Register_LoginPage)
        self.usernameTbx.setMinimumSize(QtCore.QSize(250, 30))
        self.usernameTbx.setMaximumSize(QtCore.QSize(250, 30))
        self.usernameTbx.setMouseTracking(True)
        self.usernameTbx.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.usernameTbx.setObjectName("usernameTbx")
        self.gridLayout_3.addWidget(self.usernameTbx, 2, 1, 1, 1)
        self.pwLbl = QtWidgets.QLabel(self.Register_LoginPage)
        self.pwLbl.setMinimumSize(QtCore.QSize(250, 15))
        self.pwLbl.setMaximumSize(QtCore.QSize(250, 15))
        self.pwLbl.setObjectName("pwLbl")
        self.gridLayout_3.addWidget(self.pwLbl, 5, 1, 1, 1)
        self.pw2Tbx = QtWidgets.QLineEdit(self.Register_LoginPage)
        self.pw2Tbx.setMinimumSize(QtCore.QSize(250, 30))
        self.pw2Tbx.setMaximumSize(QtCore.QSize(250, 30))
        self.pw2Tbx.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pw2Tbx.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.pw2Tbx.setObjectName("pw2Tbx")
        self.gridLayout_3.addWidget(self.pw2Tbx, 8, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(247, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem5, 16, 1, 1, 1)
        self.stackedWidget.addWidget(self.Register_LoginPage)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.PageFrame, 1, 1, 1, 1)
        self.HeadFrame = QtWidgets.QFrame(self.centralwidget)
        self.HeadFrame.setMinimumSize(QtCore.QSize(850, 50))
        self.HeadFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.HeadFrame.setStyleSheet("")
        self.HeadFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HeadFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HeadFrame.setObjectName("HeadFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.HeadFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.IconLbl = QtWidgets.QLabel(self.HeadFrame)
        self.IconLbl.setMinimumSize(QtCore.QSize(50, 0))
        self.IconLbl.setMaximumSize(QtCore.QSize(50, 16777215))
        self.IconLbl.setText("")
        self.IconLbl.setObjectName("IconLbl")
        self.horizontalLayout.addWidget(self.IconLbl)
        self.NameLbl = QtWidgets.QLabel(self.HeadFrame)
        self.NameLbl.setStyleSheet("font: 75 11pt \"Century Gothic\";\n"
"color:white;")
        self.NameLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.NameLbl.setObjectName("NameLbl")
        self.horizontalLayout.addWidget(self.NameLbl)
        spacerItem6 = QtWidgets.QSpacerItem(656, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.MinimizeBtn = QtWidgets.QPushButton(self.HeadFrame)
        self.MinimizeBtn.setMinimumSize(QtCore.QSize(15, 15))
        self.MinimizeBtn.setMaximumSize(QtCore.QSize(15, 15))
        self.MinimizeBtn.setStyleSheet("#MinimizeBtn{    \n"
"    background-color: rgb(35, 143, 219);\n"
"    border-radius:1px;\n"
"}\n"
"#MinimizeBtn:hover{\n"
"    \n"
"    background-color: rgb(31, 124, 191);\n"
"}\n"
"#MinimizeBtn:pressed{\n"
"    \n"
"    \n"
"    background-color: rgb(41, 166, 255);\n"
"}")
        self.MinimizeBtn.setText("")
        self.MinimizeBtn.setObjectName("MinimizeBtn")
        self.horizontalLayout.addWidget(self.MinimizeBtn)
        self.FullScreenBtn = QtWidgets.QPushButton(self.HeadFrame)
        self.FullScreenBtn.setMinimumSize(QtCore.QSize(15, 15))
        self.FullScreenBtn.setMaximumSize(QtCore.QSize(15, 15))
        self.FullScreenBtn.setStyleSheet("#FullScreenBtn{    \n"
"    background-color: rgb(123, 214, 32);\n"
"border-radius:1px;\n"
"}\n"
"#FullScreenBtn:hover{\n"
"    background-color: rgb(107, 186, 28);\n"
"}\n"
"#FullScreenBtn:pressed{\n"
"    \n"
"    background-color: rgb(147, 255, 38);\n"
"}")
        self.FullScreenBtn.setText("")
        self.FullScreenBtn.setObjectName("FullScreenBtn")
        self.horizontalLayout.addWidget(self.FullScreenBtn)
        self.ExitBtn = QtWidgets.QPushButton(self.HeadFrame)
        self.ExitBtn.setMinimumSize(QtCore.QSize(15, 15))
        self.ExitBtn.setMaximumSize(QtCore.QSize(15, 15))
        self.ExitBtn.setStyleSheet("#ExitBtn{    \n"
"background-color: rgb(212, 43, 15);\n"
"border-radius:1px;\n"
"}\n"
"#ExitBtn:hover{\n"
"    background-color: rgb(181, 24, 2);\n"
"}\n"
"#ExitBtn:pressed{\n"
"    \n"
"    background-color: rgb(255, 24, 2);\n"
"}")
        self.ExitBtn.setText("")
        self.ExitBtn.setObjectName("ExitBtn")
        self.horizontalLayout.addWidget(self.ExitBtn)
        self.gridLayout.addWidget(self.HeadFrame, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        MainWindow.setWindowIcon(QtGui.QIcon("icons/marelogo.ico"))

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Film Application | Maresal PRM"))
        self.homeBtn.setText(_translate("MainWindow", "Anasayfa"))
        self.filmsBtn.setText(_translate("MainWindow", "Filmler"))
        self.filmAddBtn.setText(_translate("MainWindow", "Film Ekleme"))
        self.registerHomeBtn.setText(_translate("MainWindow", "Kayıt Ol"))
        self.LoginBtn.setText(_translate("MainWindow", "Giriş Yap"))
        self.LogoutBtn.setText(_translate("MainWindow", "Çıkış Yap"))
        self.settingBtn.setText(_translate("MainWindow", "Ayarlar"))
        self.vizyonThLbl.setText(_translate("MainWindow", "Vizyon Tarini : "))
        self.OzetLbl.setText(_translate("MainWindow", "Özet"))
        self.originalNameLbl.setText(_translate("MainWindow", "Orijinal Adı : "))
        self.filmNameLbl.setText(_translate("MainWindow", "Film İsmi"))
        self.categoryFilmLbl.setText(_translate("MainWindow", "Kategori :"))
        self.directorNameLbl.setText(_translate("MainWindow", "Yönetmen : "))
        self.label_7.setText(_translate("MainWindow", "Filmin Orijinal Ismi :"))
        self.label_8.setText(_translate("MainWindow", "Vizyon Tarihi :"))
        self.label_6.setText(_translate("MainWindow", "Film Kategorisi :"))
        self.label_5.setText(_translate("MainWindow", "Yönetmen Ismi :"))
        self.label_4.setText(_translate("MainWindow", "Film Ismi :"))
        self.label_3.setText(_translate("MainWindow", "Film Özeti :"))
        self.filmKayitLbl.setText(_translate("MainWindow", "Film Kayıt Ekranı"))
        self.clearBtn.setText(_translate("MainWindow", "Temizle"))
        self.label_10.setText(_translate("MainWindow", "Filmin Fragman Video Urlsi :"))
        self.label_9.setText(_translate("MainWindow", "Filmin Resim Urlsi :"))
        self.saveFilmBtn.setText(_translate("MainWindow", "Kaydet"))
        self.securityQLbl.setText(_translate("MainWindow", "Güvenlik Sorunuz :"))
        self.usernameLbl.setText(_translate("MainWindow", "Kullanıcı Adı :"))
        self.emailLbl.setText(_translate("MainWindow", "E-mail :"))
        self.loginBtn.setText(_translate("MainWindow", "Giriş Yap"))
        self.pwLbl2.setText(_translate("MainWindow", "Tekrar Şifreniz :"))
        self.registerBtn.setText(_translate("MainWindow", "Kayıt Ol"))
        self.pwLbl.setText(_translate("MainWindow", "Şifreniz :"))
        self.NameLbl.setText(_translate("MainWindow", "Film Application | Maresal Programming"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
